apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 # ingressClassName: nginx
  tls:
  - hosts:
    - test.anaeleboo.com
    secretName: example-tls2
  rules:
  - host: test.anaeleboo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-service
            port:
              number: 80
  
